version: '3.0'

services:
  db:
    expose:
      - 5432

  django:
    expose:
      - 8080

  nginx:
    ports:
      - "80:80"
      - "443:443"

  goaccess:
    ports:
      - "7889:7889"
    expose:
      - 7889