version: '3.0'

services:
  db:
    expose:
      - 5432
    ports:
      - "5432:5432"

  django:
    expose:
      - 8080
    ports:
      - "8080:8080"

  nginx:
    ports:
      - "80:80"
      - "443:443"

  goaccess:
    expose:
      - 7889